CC		=	gcc

CFLAGS	= 	-Wall -Wextra -Werror -g

OBJDIR	=	objs
SRCDIR	=	srcs

NAME	=	philo_bonus

SRC		=	main.c \
			check_number.c \
			ft_life.c \
			ft_print_message.c \
			ft_time.c \
			philos.c \
			struct_init.c

SRC		:=	$(addprefix $(SRCDIR)/, $(SRC))
OBJ		=	$(patsubst $(SRCDIR)/%, $(OBJDIR)/%, $(SRC:.c=.o))

all:		$(NAME)

$(NAME):	$(OBJ) 
			$(CC) $(OBJ) -lpthread -o $(NAME)

$(OBJ):		$(OBJDIR)

$(OBJDIR):
			mkdir $(OBJDIR)

$(OBJDIR)/%.o:	$(SRCDIR)/%.c ./includes/philosophers.h
			$(CC) $(CFLAGS) -I ./includes -c $< -o $@

clean:
			rm -rf $(OBJDIR)

fclean:		clean
			rm -f $(NAME)

re:			fclean all

.PHONY:		all clean fclean re